[menus]
    [menus.file]
    name="File"
        [menus.file.actions]
            [menus.file.actions.exportMetaData]
            name="Export File Data"
            icon="None"
            target="fileModel"
            [menus.file.actions.importMetaData]
            name="Import File Data"
            icon="None"
            target="fileModel"
