[keckcode_deimos1d]
modulename="keckcode.deimos"
objname="deimosmask1d"
type="multi"
toolbox="keck1d"
    [keckcode_deimos1d.attributes]
    zguess="float"
    confidence="string"
    [keckcode_deimos1d.tools]
    SpectrumNavigatorTool.next="nextGraph"
    SpectrumNavigatorTool.prev="prevGraph"
    SmoothingTool="smoothGraph"
    ZGuessTool="zGuessUpdate"
    LineUpdateTool="linesUpdate"
    ModelTool="model"
