[general]
    [general.widgets]
    import="spectralyze.gui.Views.Widgets.spectraNavigatorWidgets"
    navigator="SpectrumNavigatorTool"
    smoothing="SmoothingTool"
    zguess="ZGuessTool"
    lineupdate="LineUpdateTool"

[keck1d]
    [keck1d.widgets]
    lineupdate = "keckcode"